### ISSUE TITLE
markdownlint-cli2 throws an exception for a custom rule

### ISSUE THREAD

**Issue by holamgadol** [DavidAnson/markdownlint-cli2#144] opened 2023-03-31 07:21 UTC
Thank you for your great linting tools. They really help, but now I stuck with an error.

I'm making a custom rule for _markdownlint_. Previously, I successfully made some. But unfortunately, after some updates, _markdownlint-cli2_ started to throw an exception for every custom rule. Everything works like a charm from the JS API, but fails in the case of _markdownlint-cli2_.

Here is my setup:
- _inline-code-check.js_
```js
// @ts-check

'use strict'

const { forEachInlineChild, addError } = require('markdownlint-rule-helpers')

module.exports = {
  names: ['inline-code-check'],
  description: 'Rule that reports an error for any inline code',
  tags: ['test'],
  function: (params, onError) => {
    forEachInlineChild(params, 'code_inline', async function forToken (token) {
      addError(onError, token.lineNumber, 'Inline code')
    })
  }
}
```
- _.markdownlint-cli2.jsonc_
```json
{
  "customRules": [
    "./lib/inline-code-check"

  ],
  "config": {
    "default": true,
    "inline-code-check": true
  }
}
```

- _inlinecode.md_
```markdown
# Header

### wrong header

`some inline code`

```

- _test.js_
```js
const inlineCodeCheck = require('./lib/inline-code-check.js')
const markdownlint = require('markdownlint')

const options = {
  files: [
    './inlinecode.md'
  ],
  config: {
    default: true,
    'inline-code-check': true
  },
  customRules: [inlineCodeCheck],
  resultVersion: 2
}

markdownlint(options, function callback (err, result) {
  if (!err) {
    console.log(result.toString())
  }
})
```

Using API
```shell
/usr/local/bin/node /Users/user/test.js
./inlinecode.md: 5: inline-code-check Rule that reports an error for any inline code [Inline code]
./inlinecode.md: 3: MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h3]

Process finished with exit code 0
```

Using markdownlint-cli2
```shell
$ markdownlint-cli2 ./inlinecode.md
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Finding: ./inlinecode.md
Linting: 1 file(s)
Summary: 2 error(s)
inlinecode.md:1 inline-code-check Rule that reports an error for any inline code [This rule threw an exception: Cannot read properties of undefined (reading 'markdownit')]
inlinecode.md:3 MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h3]
```

What may cause such problems?

UPD

I bumped markdownlint version in markdownlint-cli2 and the error has gone
```shell
$ markdownlint-cli2 ./inlinecode.md
markdownlint-cli2 v0.6.0 (markdownlint v0.28.0)
Finding: ./inlinecode.md
Linting: 1 file(s)
Summary: 2 error(s)
inlinecode.md:3 MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h3]
inlinecode.md:5 inline-code-check Rule that reports an error for any inline code [Inline code]
```

**Comment by DavidAnson** [comment] 2023-03-31 15:47
This looks like a duplicate of <https://github.com/DavidAnson/markdownlint/issues/759>. If your custom rule is using the installed version of markdownlint-rule-helpers instead of specifying it's own, then changes in the newest version may cause problems when run with an older markdownlint (as currently used by markdownlint-cli2).

**Comment by holamgadol** [comment] 2023-03-31 16:20
Thanks for a clue!
I've downgraded _markdownlint_ and _markdownlint-rule-helpers_ in _package.json_ and everything works fine now
```json
    "markdownlint": "^0.27.0",
    "markdownlint-rule-helpers": "^0.18.0"
   ```

**Closed** 2023-03-31 21:27 UTC
Labels: question
